import type { EmotionKey } from './emotionTypes';

export const emotionKeywords: Record<EmotionKey, { keywords: string[]; phrases: string[] }> = {
  elated: { keywords: ['elated', 'euphoric', 'ecstatic', 'thrilled', 'overjoyed', 'amazing', 'alive', 'unstoppable'], phrases: ['on top of the world'] },
  happy: { keywords: ['happy', 'good', 'joyful', 'glad', 'cheerful', 'great', 'pleased', 'joy'], phrases: [] },
  content: { keywords: ['content', 'satisfied', 'enough', 'okay'], phrases: ['okay in a good way', 'at peace'] },
  grateful: { keywords: ['grateful', 'thankful', 'appreciative', 'blessed', 'lucky'], phrases: [] },
  proud: { keywords: ['proud', 'impressed'], phrases: ['respect myself', 'impressed with myself', 'becoming better'] },
  accomplished: { keywords: ['accomplished', 'achieved', 'finished', 'completed', 'won', 'success'], phrases: [] },
  confident: { keywords: ['confident', 'capable', 'self-assured', 'strong'], phrases: ['trust myself'] },
  excited: { keywords: ['excited', 'eager', 'hyped', 'pumped'], phrases: ['looking forward'] },
  hopeful: { keywords: ['hopeful', 'optimistic', 'encouraged'], phrases: ['things can improve'] },
  inspired: { keywords: ['inspired', 'creative', 'sparked', 'moved', 'ideas'], phrases: [] },
  motivated: { keywords: ['motivated', 'driven', 'disciplined', 'hungry'], phrases: ['locked in'] },
  determined: { keywords: ['determined', 'committed', 'persistent'], phrases: ['not quitting'] },
  peaceful: { keywords: ['peaceful', 'still', 'quiet', 'serene', 'soft'], phrases: [] },
  calm: { keywords: ['calm', 'grounded', 'steady', 'relaxed', 'centered'], phrases: [] },
  relieved: { keywords: ['relieved', 'lighter'], phrases: ['weight lifted', 'finally okay'] },
  loved: { keywords: ['loved', 'cherished', 'seen', 'valued'], phrases: ['cared for'] },
  connected: { keywords: ['connected', 'close', 'bonded', 'together'], phrases: ['less alone'] },
  accepted: { keywords: ['accepted', 'welcome', 'belonging'], phrases: ['no need to perform'] },
  safe: { keywords: ['safe', 'secure', 'protected'], phrases: ['guard down'] },
  playful: { keywords: ['playful', 'silly', 'fun', 'unserious', 'lighthearted'], phrases: [] },
  curious: { keywords: ['curious', 'wondering', 'interested'], phrases: ['drawn to'] },
  amazed: { keywords: ['amazed', 'awestruck', 'wonder', 'wow', 'beautiful'], phrases: [] },
  surprised: { keywords: ['surprised', 'shocked', 'unexpected'], phrases: ['caught off guard'] },
  nostalgic: { keywords: ['nostalgic', 'remembering'], phrases: ['miss the past', 'old times'] },
  tender: { keywords: ['tender', 'soft', 'delicate', 'gentle'], phrases: [] },
  compassionate: { keywords: ['compassionate', 'empathy', 'understanding', 'care'], phrases: [] },
  sad: { keywords: ['sad', 'down', 'low', 'heavy', 'blue', 'upset'], phrases: [] },
  hurt: { keywords: ['hurt', 'wounded', 'painful', 'stung', 'crushed'], phrases: [] },
  disappointed: { keywords: ['disappointed', 'discouraged'], phrases: ['let down', 'hoped for more'] },
  heartbroken: { keywords: ['heartbroken', 'brokenhearted', 'devastated', 'crushed', 'shattered'], phrases: [] },
  grieving: { keywords: ['grieving', 'grief', 'mourning', 'loss'], phrases: ['missing someone'] },
  lonely: { keywords: ['lonely', 'alone', 'isolated', 'disconnected'], phrases: ['left out'] },
  rejected: { keywords: ['rejected', 'unwanted', 'dismissed'], phrases: ['not chosen'] },
  abandoned: { keywords: ['abandoned', 'deserted', 'forgotten'], phrases: ['left behind'] },
  longing: { keywords: ['longing', 'yearning', 'craving', 'wanting', 'missing'], phrases: [] },
  regretful: { keywords: ['regret', 'regretful'], phrases: ['wish i had', 'should have'] },
  guilty: { keywords: ['guilty', 'fault', 'responsible'], phrases: ['i messed up', 'my fault'] },
  ashamed: { keywords: ['ashamed', 'shame', 'pathetic', 'unworthy'], phrases: ['not good enough'] },
  embarrassed: { keywords: ['embarrassed', 'humiliated', 'awkward', 'cringe'], phrases: [] },
  insecure: { keywords: ['insecure', 'inadequate', 'replaceable'], phrases: ['not enough'] },
  inferior: { keywords: ['inferior', 'behind'], phrases: ['less than', 'worse than'] },
  jealous: { keywords: ['jealous', 'possessive', 'threatened'], phrases: ['scared of losing'] },
  envious: { keywords: ['envious', 'envy', 'comparison'], phrases: ['wish i had that'] },
  anxious: { keywords: ['anxious', 'anxiety', 'nervous', 'uneasy'], phrases: ['on edge'] },
  worried: { keywords: ['worried', 'concern', 'afraid'], phrases: ['afraid something will happen'] },
  afraid: { keywords: ['afraid', 'scared', 'fearful', 'unsafe', 'terrified'], phrases: [] },
  panicked: { keywords: ['panicked', 'panic', 'spiraling'], phrases: ['freaking out'] },
  dreadful: { keywords: ['dread', 'dreadful', 'doom'], phrases: ['terrible future'] },
  overwhelmed: { keywords: ['overwhelmed', 'drowning', 'overloaded'], phrases: ['too much'] },
  stressed: { keywords: ['stressed', 'pressure', 'urgent', 'tense'], phrases: [] },
  burned_out: { keywords: ['drained', 'depleted'], phrases: ['burned out', 'burnt out', 'no fuel', 'forcing myself'] },
  exhausted: { keywords: ['exhausted', 'tired', 'drained'], phrases: ['no energy', 'worn out'] },
  numb: { keywords: ['numb', 'blank', 'emotionless'], phrases: ['shut down'] },
  empty: { keywords: ['empty', 'hollow', 'meaningless'], phrases: ['nothing inside'] },
  detached: { keywords: ['detached', 'distant', 'disconnected'], phrases: [] },
  apathetic: { keywords: ['apathetic', 'indifferent', 'apathy'], phrases: ['do not care', "don't care"] },
  angry: { keywords: ['angry', 'mad', 'pissed', 'upset', 'rage'], phrases: [] },
  furious: { keywords: ['furious', 'enraged', 'livid', 'boiling'], phrases: [] },
  irritated: { keywords: ['irritated', 'annoyed', 'bothered', 'agitated'], phrases: [] },
  frustrated: { keywords: ['frustrated', 'stuck', 'blocked'], phrases: ['fed up'] },
  resentful: { keywords: ['resentful', 'used', 'unfair'], phrases: ['taken for granted', 'nobody notices', 'giving so much'] },
  bitter: { keywords: ['bitter', 'hardened', 'owed'], phrases: ['unresolved hurt'] },
  betrayed: { keywords: ['betrayed', 'backstabbed'], phrases: ['trust broken', 'lied to'] },
  disgusted: { keywords: ['disgusted', 'repulsed', 'sickened'], phrases: ['grossed out'] },
  contemptuous: { keywords: ['contempt', 'judgmental', 'pathetic'], phrases: ['beneath me'] },
  confused: { keywords: ['confused', 'unclear', 'lost'], phrases: ['do not understand', "don't understand"] },
  conflicted: { keywords: ['conflicted', 'torn'], phrases: ['mixed feelings', 'two sides'] },
  indecisive: { keywords: ['indecisive'], phrases: ['cannot decide', "can't decide", 'second guessing'] },
  uncertain: { keywords: ['uncertain', 'unsure', 'unclear'], phrases: ['not sure'] },
  doubtful: { keywords: ['doubtful', 'questioning'], phrases: ['losing belief'] },
  skeptical: { keywords: ['skeptical', 'suspicious'], phrases: ['not convinced'] },
  bored: { keywords: ['bored', 'dull', 'uninterested', 'unstimulated'], phrases: [] },
  tame: { keywords: ['tame', 'average', 'normal'], phrases: ['nothing special'] },
  neutral: { keywords: ['neutral', 'fine', 'okay', 'meh'], phrases: ['neither good nor bad', 'neither bad nor good'] },
  restless: { keywords: ['restless', 'unsettled'], phrases: ['need change', 'cannot sit still'] },
  stuck: { keywords: ['stuck', 'blocked'], phrases: ['same cycle', 'no progress'] },
  trapped: { keywords: ['trapped'], phrases: ['no way out', 'boxed in'] },
  impatient: { keywords: ['impatient', 'rushing', 'hurry'], phrases: ['cannot wait'] },
  discouraged: { keywords: ['discouraged'], phrases: ['progress feels impossible'] },
  defeated: { keywords: ['defeated', 'done', 'lost', 'hopeless'], phrases: [] },
  powerless: { keywords: ['powerless', 'helpless'], phrases: ['no control'] },
  vulnerable: { keywords: ['vulnerable', 'raw'], phrases: ['exposed emotionally'] },
  exposed: { keywords: ['exposed'], phrases: ['too visible', 'seen through'] },
  misunderstood: { keywords: ['misunderstood'], phrases: ['no one gets it', 'hard to explain'] },
  invisible: { keywords: ['invisible', 'unseen', 'unnoticed', 'ignored'], phrases: [] },
  unappreciated: { keywords: ['unappreciated'], phrases: ['ignored effort', 'taken for granted'] },
  pressured: { keywords: ['pressured', 'expectations', 'must'], phrases: ['have to'] },
  guilty_pleasure: { keywords: [], phrases: ['guilty pleasure', 'should not enjoy', 'embarrassed to like'] },
  awkward: { keywords: ['awkward', 'cringe', 'uncomfortable'], phrases: [] },
  resigned: { keywords: ['resigned'], phrases: ['giving up', 'accepted it', 'no point'] },
  courageous: { keywords: ['courageous', 'brave'], phrases: ['did it scared'] },
  humbled: { keywords: ['humbled', 'corrected'], phrases: ['ego checked', 'still learning'] },
  trusting: { keywords: ['trusting', 'trust'], phrases: ['opened up', 'believed in'] },
  suspicious: { keywords: ['suspicious', 'pattern'], phrases: ['feels off', 'red flag'] },
  optimistic: { keywords: ['optimistic', 'positive', 'possibility'], phrases: ['better future'] },
  melancholic: { keywords: ['melancholic', 'bittersweet'], phrases: ['beautiful and sad', 'painful and precious'] },
};
